spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          delimiter: ;
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: target/create-schema.sql
