spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/postgres
    username: boilerplate
    password: apppass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.hbm2ddl.auto: validate
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.time_zone: UTC
      hibernate.enable_lazy_load_no_trans: true
    show-sql: true
  flyway:
    enabled: true
